"""
AgriFlow PM Agent — GitHub Actions cron으로 5시간마다 실행되는 자동 PM.

흐름:
1. README + 최근 dev 브랜치 git log + 코드 인벤토리 수집
2. Anthropic Claude Opus 4.x 호출 → 작업 후보 마크다운 생성
3. GitHub Issue 생성 (라벨 'pm-cycle')
4. ntfy.sh 모바일 푸시 (이슈 URL 포함)

환경 변수 (GitHub Actions Secrets):
- ANTHROPIC_API_KEY: Anthropic 콘솔에서 발급
- NTFY_TOPIC: ntfy.sh 토픽명 (예: agriflow-pm-xK9p2)
- GITHUB_TOKEN: Actions가 자동 주입
"""
from __future__ import annotations

import datetime
import os
import subprocess
import sys
import urllib.request
import urllib.error

from anthropic import Anthropic

# ─────────────────────────────────────────────────────────────
# 1. 컨텍스트 수집
# ─────────────────────────────────────────────────────────────

def read_text(path: str, fallback: str = "") -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return fallback


def safe_subprocess(args: list[str], default: str = "") -> str:
    try:
        return subprocess.check_output(args, stderr=subprocess.DEVNULL).decode("utf-8", errors="replace")
    except subprocess.CalledProcessError:
        return default


readme = read_text("README.md", "(README.md 없음)")

# 최근 24시간 dev 커밋 (없으면 최근 30개)
git_log = safe_subprocess(
    ["git", "log", "dev", "--since=24.hours.ago", "--oneline", "--no-merges"]
)
if not git_log.strip():
    git_log = safe_subprocess(["git", "log", "dev", "-30", "--oneline", "--no-merges"])
git_log = git_log.strip() or "(최근 커밋 없음)"

# 코드 인벤토리 — 핵심 디렉토리만, 응답 토큰 절약
file_tree = safe_subprocess([
    "git", "ls-tree", "-r", "--name-only", "dev",
    "--", "frontend/app", "frontend/components", "frontend/hooks",
    "backend/app/api", "backend/app/services", "backend/app/schemas",
    "supabase/migrations",
])
file_tree_lines = file_tree.strip().splitlines()
# 너무 많으면 잘라냄
if len(file_tree_lines) > 250:
    file_tree = "\n".join(file_tree_lines[:250]) + f"\n... (총 {len(file_tree_lines)}개 파일, 250개만 표시)"

# 직전 PM 사이클 결과 (있으면 PM이 자체 피드백)
prev_cycle = safe_subprocess([
    "gh", "issue", "list",
    "--label", "pm-cycle",
    "--limit", "1",
    "--state", "all",
    "--json", "title,body",
    "--jq", ".[0] | \"### 직전 사이클: \" + .title + \"\\n\" + .body",
])
prev_cycle = prev_cycle.strip()[:3000] if prev_cycle.strip() else "(첫 사이클)"

user_input = f"""
# README
{readme[:6000]}

# 최근 dev 브랜치 커밋
{git_log[:3000]}

# 코드 인벤토리 (frontend·backend·migrations)
{file_tree}

# 직전 PM 사이클 결과 (이번 추천 시 중복 회피용)
{prev_cycle}
"""

# ─────────────────────────────────────────────────────────────
# 2. Claude Opus 호출
# ─────────────────────────────────────────────────────────────

system_prompt = read_text(".github/scripts/pm-system-prompt.md")
if not system_prompt.strip():
    print("ERROR: .github/scripts/pm-system-prompt.md 가 비어있음", file=sys.stderr)
    sys.exit(1)

client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

response = client.messages.create(
    model="claude-opus-4-5",
    max_tokens=4000,
    system=system_prompt,
    messages=[{"role": "user", "content": user_input}],
)
report = response.content[0].text.strip()

# ─────────────────────────────────────────────────────────────
# 3. GitHub Issue 생성
# ─────────────────────────────────────────────────────────────

ts_kst = (datetime.datetime.utcnow() + datetime.timedelta(hours=9)).strftime("%Y-%m-%d %H:%M KST")
title = f"PM Report — {ts_kst}"

# pm-cycle 라벨 자동 생성 (이미 있으면 무시)
subprocess.run(
    ["gh", "label", "create", "pm-cycle", "--color", "5319E7", "--description", "PM 자동 사이클 보고", "--force"],
    check=False,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)

issue_body = f"""{report}

---
*🤖 Auto-generated by PM Agent · {ts_kst}*
*Model: claude-opus-4-5 · 다음 사이클: 약 5시간 뒤*
"""

issue_create = subprocess.run(
    ["gh", "issue", "create", "--title", title, "--body", issue_body, "--label", "pm-cycle"],
    capture_output=True,
    text=True,
)
if issue_create.returncode != 0:
    print(f"ERROR: gh issue create 실패: {issue_create.stderr}", file=sys.stderr)
    sys.exit(1)

issue_url = issue_create.stdout.strip()
print(f"✅ Issue 생성: {issue_url}")

# ─────────────────────────────────────────────────────────────
# 4. ntfy.sh 모바일 푸시
# ─────────────────────────────────────────────────────────────

topic = os.environ.get("NTFY_TOPIC")
if topic:
    # 본문은 추천 작업 첫 부분만 발췌 (알림 미리보기)
    preview_lines = [ln for ln in report.splitlines() if ln.strip().startswith("1.") or ln.strip().startswith("2.")][:2]
    preview = "\n".join(preview_lines) if preview_lines else "PM 사이클 완료. 작업 후보 검토 필요."
    push_body = f"{preview}\n\n전체 보기 → 탭"

    req = urllib.request.Request(
        f"https://ntfy.sh/{topic}",
        data=push_body.encode("utf-8"),
        headers={
            "Title": "AgriFlow PM Report",
            "Priority": "default",
            "Tags": "memo,clipboard",
            "Click": issue_url,
            "Actions": f"view, GitHub에서 보기, {issue_url}, clear=true",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            print(f"✅ ntfy 푸시 발송: HTTP {resp.status}")
    except urllib.error.URLError as e:
        # 푸시 실패해도 이슈는 생성됨 — best-effort
        print(f"⚠️  ntfy 푸시 실패 (이슈는 정상 생성): {e}")
else:
    print("⚠️  NTFY_TOPIC 환경변수 없음 — 모바일 푸시 생략")

print("\n✅ PM 사이클 완료")
